AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda function that returns variables.
Resources:
  simple:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: 's3://terraform-serverless-example-nikhil/lambda_function.zip'
      Description: An AWS Lambda function that echo three variables.
      MemorySize: 128
      Timeout: 3
